# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "2048"
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end
  config.vm.hostname = "p4"
  config.vm.provision "file", source: "p4-wallpaper.png", destination: "/home/vagrant/p4-wallpaper.png"
  config.vm.provision "shell", path: "root-bootstrap.sh"
  config.vm.provision "shell", privileged: false, path: "user-bootstrap.sh"
end
